# Generated by Django 4.2.7 on 2023-12-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed ad nisi asperiores amet est pariatur corrupti. Molestias aperiam natus adipisci officiis veniam quo. Hic dicta beatae voluptate accusantium, nostrum maiores.', max_length=500),
        ),
    ]
