# Generated by Django 4.2.7 on 2023-12-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_item_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='prod_code',
            field=models.IntegerField(default=50),
        ),
    ]
