# Generated by Django 4.2.7 on 2023-12-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_item_prod_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='for_user',
            field=models.CharField(default='RestOwner', max_length=100),
        ),
    ]
